import React, { createContext, useContext, useMemo, useState } from "react";

const translations = {
  en: {
    home: "Home",
    listings: "Vacation Rentals",
    forSale: "For Sale",
    ownerServices: "Owner Services",
    leads: "Lead Center",
    admin: "Admin",
    adminLogin: "Admin Login",
    bookNow: "Book Now",
    contact: "Contact",
    directBookings: "Direct bookings • Owner portal • Admin operations",
    heroTitle: "Next-level branded platform for Playa Escondida Vacation Homes.",
    heroText: "This build adds your logo, a stronger sales personality, lead funnels, booking drafts, calendar scaffolding, and a cleaner business structure for rentals, sales, and owner services.",
    exploreListings: "Explore Listings",
    openDashboard: "Open Dashboard",
    mainSections: "Main Sections",
    threeLinesTitle: "Vacation Rentals | For Sale | Owner Services",
    threeLinesText: "The site is organized into three clear business lines so guests, buyers, and owners each have a dedicated path.",
    openSection: "Open Section",
    betterCallSaul: "Better call Saul",
    leadCenterTitle: "Separate lead forms for rentals, buyers, and owners.",
    bookingCalendarTitle: "Live booking calendar scaffold.",
    vacationRentalInquiry: "Vacation Rental Inquiry",
    propertyBuyerInquiry: "Property Buyer Inquiry",
    ownerServicesInquiry: "Owner Services Inquiry",
    fullName: "Full name",
    email: "Email",
    phone: "Phone",
    message: "Message",
    saveLead: "Save Lead",
    booking: "Booking",
    completeReservation: "Complete your reservation",
    firstName: "First name",
    lastName: "Last name",
    checkInDate: "Check-in date",
    checkOutDate: "Check-out date",
    guests: "Guests",
    promoCode: "Promo code",
    specialRequests: "Special requests",
    backToProperty: "Back to Property",
    createBookingPayment: "Create Booking + Payment Step",
    reservationSummary: "Reservation summary",
    accommodation: "Accommodation",
    cleaningFee: "Cleaning fee",
    total: "Total",
    perNight: "per night",
    askingPrice: "asking price",
    requestInfo: "Request Info",
    salesTitle: "Property listings for sale.",
    salesText: "This section is for units and properties available for purchase, separate from vacation rentals.",
    ownerTitle: "Owner visibility for performance, stays, and payouts.",
    ownerText: "This page presents the owner-facing services area with performance visibility, statements, payouts, and support actions.",
    monthlyStatement: "Monthly statement",
    ownerActions: "Owner actions",
    signIn: "Sign In",
    rentals: "Vacation Rentals",
    leadSaved: "lead saved",
    language: "Language",
    english: "English",
    spanish: "Español",
  },
  es: {
    home: "Inicio",
    listings: "Alquileres Vacacionales",
    forSale: "En Venta",
    ownerServices: "Servicios para Propietarios",
    leads: "Centro de Leads",
    admin: "Admin",
    adminLogin: "Acceso Admin",
    bookNow: "Reservar",
    contact: "Contacto",
    directBookings: "Reservas directas • Portal de propietarios • Administración",
    heroTitle: "Plataforma bilingüe de Playa Escondida Vacation Homes.",
    heroText: "Esta versión agrega tu logo, una personalidad comercial más fuerte, embudos de leads, borradores de reserva, calendario base y una estructura más clara para alquileres, ventas y servicios al propietario.",
    exploreListings: "Ver Alquileres",
    openDashboard: "Abrir Panel",
    mainSections: "Secciones Principales",
    threeLinesTitle: "Alquileres Vacacionales | En Venta | Servicios para Propietarios",
    threeLinesText: "El sitio está organizado en tres líneas de negocio claras para que huéspedes, compradores y propietarios tengan su propio camino.",
    openSection: "Abrir Sección",
    betterCallSaul: "Better call Saul",
    leadCenterTitle: "Formularios separados para alquileres, compradores y propietarios.",
    bookingCalendarTitle: "Calendario de reservas base.",
    vacationRentalInquiry: "Consulta de Alquiler Vacacional",
    propertyBuyerInquiry: "Consulta de Compra",
    ownerServicesInquiry: "Consulta de Servicios para Propietarios",
    fullName: "Nombre completo",
    email: "Correo",
    phone: "Teléfono",
    message: "Mensaje",
    saveLead: "Guardar Lead",
    booking: "Reserva",
    completeReservation: "Completa tu reserva",
    firstName: "Nombre",
    lastName: "Apellido",
    checkInDate: "Fecha de entrada",
    checkOutDate: "Fecha de salida",
    guests: "Huéspedes",
    promoCode: "Código promocional",
    specialRequests: "Solicitudes especiales",
    backToProperty: "Volver a la Propiedad",
    createBookingPayment: "Crear Reserva + Paso de Pago",
    reservationSummary: "Resumen de reserva",
    accommodation: "Alojamiento",
    cleaningFee: "Limpieza",
    total: "Total",
    perNight: "por noche",
    askingPrice: "precio de venta",
    requestInfo: "Solicitar Info",
    salesTitle: "Propiedades en venta.",
    salesText: "Esta sección es para unidades y propiedades disponibles para compra, separadas de los alquileres vacacionales.",
    ownerTitle: "Visibilidad del propietario sobre desempeño, estadías y pagos.",
    ownerText: "Esta página presenta el área de servicios para propietarios con visibilidad de rendimiento, estados de cuenta, pagos y acciones de soporte.",
    monthlyStatement: "Estado de cuenta mensual",
    ownerActions: "Acciones del propietario",
    signIn: "Ingresar",
    rentals: "Alquileres Vacacionales",
    leadSaved: "lead guardado",
    language: "Idioma",
    english: "English",
    spanish: "Español",
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");

  const value = useMemo(() => ({
    lang,
    setLang,
    t(key) {
      return translations[lang]?.[key] ?? translations.en[key] ?? key;
    }
  }), [lang]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
